kind: Deployment
apiVersion: apps/v1
metadata:
  name: users-api
  labels:
    app: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: registry.gitlab.com/guilherme.hub2b/catoou.repo/users-api
          env:
            - name: MongoDb.ConnectionString
              value: mongodb://root:5oPHY9A79y@catoou-default-mongodb.databases:27017/?authSource=admin&readPreference=primary&appname=ConfigApi&ssl=false
            - name: Credentials.Host
              value: https://kg-kong-admin.kong:8444/consumers/frontend/basic-auth
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: gitlab
---
kind: Service
apiVersion: v1
metadata:
  name: users-api
spec:
  selector:
    app: users-api
  ports:
  - protocol: TCP
    port: 5000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: users-api-nodeport
spec:
  type: NodePort
  selector:
    app: users-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: users-api-loadbalancer
  spec:
    selector:
      app: users-api
    ports:
      - port: 5000
        targetPort: 5000
    type: LoadBalancer